plugins {
    id "java-library"
    id "maven-publish"
}

VersionCatalog libs = project.extensions.getByType(VersionCatalogsExtension).named("libs")

String version = libs.findVersion("enchanted").get()
String mcVersion = libs.findVersion("minecraft").get()
String mcVersionRange = libs.findVersion("minecraft.range").get()
String neoVersion = libs.findVersion("neoforge").get()
String neoLoaderVersionRange = libs.findVersion("neoforge.loader.range").get()
String fapiVersion = libs.findVersion("fabric.api").get()
String fabricLoaderVersion = libs.findVersion("fabric").get()

String stateobserverVersion = libs.findVersion("stateobserver").get()
String geckolibVersion = libs.findVersion("geckolib").get()
String modopediaVersion = libs.findVersion("modopedia").get()
String forgeconfigapiVersion = libs.findVersion("forgeconfigapi").get()

base {
    archivesName = "enchanted-${project.name}-$mcVersion"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
["apiElements", "runtimeElements", "sourcesElements", "javadocElements"].each { variant ->
    configurations."$variant".outgoing {
        capability("net.favouriteless.enchanted:${base.archivesName.get()}:$version")
        capability("net.favouriteless.enchanted:enchanted-${project.name}-$mcVersion:$version")
        capability("net.favouriteless.enchanted:enchanted:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_Enchanted" }
    }
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_Enchanted" }
    }

    manifest {
        attributes([
                "Specification-Title"    : "Enchanted",
                "Specification-Vendor"   : "Favouriteless",
                "Specification-Version"  : project.jar.archiveVersion,
                "Implementation-Title"   : project.name,
                "Implementation-Version" : project.jar.archiveVersion,
                "Implementation-Vendor"  : "Favouriteless",
                "Built-On-Minecraft"     : mcVersion
        ])
    }
}

processResources {
    var expandProps = [
            "version"                       : version,
            "minecraft_version"             : mcVersion,
            "minecraft_version_range"       : mcVersionRange,
            "fabric_api_version"            : fapiVersion,
            "fabric_loader_version"         : fabricLoaderVersion,
            "neoforge_version"              : neoVersion,
            "neoforge_loader_version_range" : neoLoaderVersionRange,
            "stateobserver_version"         : stateobserverVersion,
            "geckolib_version"              : geckolibVersion,
            "modopedia_version"             : modopediaVersion,
            "forgeconfigapi_version"        : forgeconfigapiVersion
    ]

    filesMatching(["pack.mcmeta", "fabric.mod.json", "META-INF/neoforge.mods.toml", "*.mixins.json"]) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }

    repositories {
        if(System.getenv("FAVOURITELESS_MAVEN_USER") == null || System.getenv("FAVOURITELESS_MAVEN_PASS") == null) {
            mavenLocal()
        }
        else maven {
            name = "FavouritelessReleases"
            url = "https://maven.favouriteless.net/releases"

            credentials {
                username = System.getenv("FAVOURITELESS_MAVEN_USER")
                password = System.getenv("FAVOURITELESS_MAVEN_PASS")
            }
        }
    }
}