modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All Rights Reserved"


[[mods]]
    modId = "enchanted"
    version = "${version}"
    displayName = "Enchanted"
    displayURL= "https://github.com/Favouriteless/Enchanted"
    logoFile = "enchanted.png"
    logoBlur = false
    credits = "Heavily inspired by Emoniph's Witchery mod"
    authors = "Favouriteless"
    description = '''Witchcraft and Occultism based on real history and folklore.'''

[[mixins]]
    config="enchanted.neoforge.mixins.json"

[[mixins]]
    config="enchanted.mixins.json"


[[dependencies.enchanted]]
    modId = "neoforge"
    type="required" #mandatory
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "minecraft"
    type="required" #mandatory
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "stateobserver"
    type="required" #mandatory
    versionRange = "[${stateobserver_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "geckolib"
    type="required" #mandatory
    versionRange = "[${geckolib_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.enchanted]]
    modId = "modopedia"
    type = "required" #mandatory
    versionRange = "[${modopedia_version},)"
    ordering = "NONE"
    side = "BOTH"